### ISSUE TITLE
add Critical Techworks to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1103]
Company: Critical Techworks 
Url: https://criticaltechworks.com/
logo: 
![image](https://user-images.githubusercontent.com/14938461/54663499-bbc72b80-4ae1-11e9-9c25-d4714fbb5288.png)

**Comment by jiri-fiala** [comment]
The logo has been cropped to content, removing the transparent area around it.
