### ISSUE TITLE
add evry to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1111]
Company: Evry
Url: https://www.evry.com/
logo: https://www.evry.com/globalassets/images_16.9_liggende/pressebilder/logo/evry-logo_rgb_word.png

**Comment by jiri-fiala** [comment]
@dmueller2001, Evry was [added on September 24th](https://github.com/openshift-cs/commons.openshift.org/commit/2f0e2393a6d398b873b16baa14cc95308007b26a). It seems this does not really update the logo, name (aside of decapitalization), neither URL. I'm gonna close it, but please feel free to reopen, if you wish to update anything particular for this participant.
