### ISSUE TITLE
update OpenshiftOpenstack.html.erb

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1155]
update this sig landing page so that it pulls blog articles from openshift.com with the tag "openstack" and has 2 non-automated linked items like the AIOps.html.erb 

https://github.com/openshift-cs/commons.openshift.org/blob/master/source/sig/OpenshiftOpenstack.html.erb

**Comment by jiri-fiala** [comment]
@dmueller2001, could you please specify the two static articles (title, link, sub-title) and their desired position (top/bottom) relative to the fetched blog articles? Also, should these two count against the total limit of fetched articles of 10, or ignore it as in case of AIOps?

**Comment by dmueller2001** [comment]
just pull articles from live blog site..
