### ISSUE TITLE
widen the blog section on the index page 

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1160]
<img width="448" alt="Screen Shot 2019-04-10 at 12 09 41 PM" src="https://user-images.githubusercontent.com/4029488/55906656-9e89f800-5b89-11e9-93e0-76b4323c94b3.png">

Please make this section as wide at least as the calendar in the above section...

**Comment by jiri-fiala** [comment]
@dmueller2001, the section is wider, a description has been added and the total number of displayed commons blog posts has been reduced to 5. [Here](https://com-stage-pro.b9ad.pro-us-east-1.openshiftapps.com/#blog) you can find a preview, please check and approve, if that's fine.
