### ISSUE TITLE
Add xOps to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1181]
Company: xOps 
URL: https://xops.it/
Logo: 
![image](https://user-images.githubusercontent.com/14938461/56904710-22574600-6a9f-11e9-939e-e4ad15dcd64b.png)

**Comment by jiri-fiala** [comment]
It seems that xOps [are using](https://xops.it/about-us) a black font variant logo too; the original has been replaced.
