### ISSUE TITLE
add xops to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1263]
Company: XOps
URL: https://xops.it
logo: 
![xOps-logo 2](https://user-images.githubusercontent.com/4029488/57982388-2f83a700-7a45-11e9-886c-67f6eef0af94.png)

**Comment by jiri-fiala** [comment]
@dmueller2001, xOps is already on the list with the proper logo (w/ transparent background and w/o the additional border) -> I'll close this issue.
