### ISSUE TITLE
add intelliSoft to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1274]
Company: intelliSoft 
Url: https://www.intellisoft.de/
Logo:

![](https://user-images.githubusercontent.com/14938461/62783781-6bb32a80-babd-11e9-9932-137fd7322f89.png)

**Comment by jiri-fiala** [comment]
@dmueller2001, this is around for a while - what about using just the company name they have on their own website as the logo?
![image](https://user-images.githubusercontent.com/14938461/62783781-6bb32a80-babd-11e9-9932-137fd7322f89.png)

**Comment by jiri-fiala** [comment]
@dmueller2001, @TanjaRepo - this is around for a while. What about using the company name in the font they have on their site, as suggested in my [previous comment](https://github.com/openshift-cs/commons.openshift.org/issues/1274#issuecomment-519927351)?

**Comment by TanjaRepo** [comment]
I am sorry that I've missed this comment @jiri-fiala - apologies.  :-/
So their company name is intelliSoft (written this way, and the logo is the one that is referred earlier :)

I think we can use it this way.
