### ISSUE TITLE
energy sig page update

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1308]
link this article to the energy sig page:

https://medium.com/@archerj/build-your-own-well-log-applications-on-containers-3c940b3b2214

as the current blog feed content is generic; this most likely means creating a new section similiar to the AIOPS landing page and linking to the energy sig google group and some other energy related content from red hat.com  (John Archer is the co-chair of this SIG)

see the AIOPS page for the style that this should copy:

<img width="1054" alt="Screen Shot 2019-06-30 at 3 35 51 PM" src="https://user-images.githubusercontent.com/4029488/60403052-fd3d8d00-9b4c-11e9-9b6d-749bc992d2e5.png">

Other video/slides to embed to: 
https://www.youtube.com/watch?v=T1NEAC7z0JU
https://www.slideshare.net/jrarcher/democratizing-data-science-on-kubernetes 

Another blog post to link to: https://medium.com/@archerj/build-your-own-seismic-applications-while-you-are-at-it-on-containers-too-3a9891f5cc05

Another BP talking about OpenShift video: https://www.youtube.com/watch?v=ZO3Z-B3MbkM

**Comment by jiri-fiala** [comment]
A possible variant of how this could look like:
https://commons-stage-pro.b9ad.pro-us-east-1.openshiftapps.com/sig/OpenShiftEnergy.html

**Comment by dmueller2001** [comment]
waiting for chair to re-engage
