### ISSUE TITLE
add Gathering at Red Hat Summit 2020

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1385]
OpenShift Commons Gathering
May 6
San Fran at Moscone Center

2 tracks; joint morning kick-off and keynotes 
1 track OpenShift 2nd smaller track OpenStack
https://www.redhat.com/en/blog/save-date-red-hat-summit-2020

**Comment by dmueller2001** [comment]
Red Hat Summit 2020
San Francisco, CA, April 27-29

Gathering will be on a SUNDAY April 26

IBM Think is the following week..FYI

**Comment by dmueller2001** [comment]
need to figure out a better way to show off add'l workshops and second track..

**Comment by jiri-fiala** [comment]
@dmueller2001, a multi-track schedule is something I did not have in mind when designing the layout. Is this something that's gonna be more usual with Commons events? If so, please create a new issue with a basic idea about the functionality and design of multi track schedules.
Thanks.
