### ISSUE TITLE
add Button to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1535]
Company: Button
URL: https://www.button.is
Logo: 
![image](https://user-images.githubusercontent.com/14938461/83262459-524eac80-a1bd-11ea-9fa3-acdd736aee52.png)

**Comment by jiri-fiala** [comment]
I've changed the text color of the logo from button.is to black (removing the alpha channel and adding a background was not ideal).
