### ISSUE TITLE
add Deutsche Bank to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1538]
Company: Deutsche Bank
URL:  https://www.db.com/company/index.htm
Logo:
![](https://user-images.githubusercontent.com/41049659/67854886-8a9be880-fb11-11e9-90e7-20006bc561aa.png)

**Comment by jiri-fiala** [comment]
@dmueller2001, the logo link points to a vertically misaligned "Deutsche Bank" text (as an image), but it looks like the actual logo is missing:

![](https://www.db.com/company/img/deutsche-bank.png)

They appear to [focus on the logo itself](https://www.db.com/company/en/media/logo-history.pdf), which can be found on their site too:

![](https://www.db.com/company/img/db_logo.gif)

Please confirm the desired logo variant.

**Comment by dmueller2001** [comment]
@TanjaRepo can you track down the correct logo to use for DB? and add it in a comment and tag @jiri-fiala when you do? many thanks

**Comment by TanjaRepo** [comment]
yes ma'am - @dmueller2001 
@jiri-fiala - will keep you updated :)

**Comment by TanjaRepo** [comment]
contacted now Emma Williamson.

**Comment by TanjaRepo** [comment]
![logotype_deutsche_bank_left_alignment_above_40mm_rgb copy](https://user-images.githubusercontent.com/41049659/67854886-8a9be880-fb11-11e9-90e7-20006bc561aa.png)

**Comment by TanjaRepo** [comment]
Would this work @jiri-fiala ? :)

**Comment by jiri-fiala** [comment]
@TanjaRepo, this is now deployed

**Comment by TanjaRepo** [comment]
Thank you @jiri-fiala again :) 
Any possibility to re-size the logo bit bigger ? :)

**Comment by TanjaRepo** [comment]
Thank you @jiri-fiala again :)
Any possibility to re-size the logo bit bigger ? :)

**Comment by jiri-fiala** [comment]
@TanjaRepo, I can't do that easily. All logo sizes are automatically adjusted to [maximum height of 60px](https://github.com/openshift-cs/commons.openshift.org/blob/master/resizer/ImageResizer.java#L42) to fit into the page layout. Logos that are overly horizontal or overly vertical may look smaller compared to some others, but we need to fit them into the grid that is used by all the logos with the current design. The closer the logo's aspect ratio is to 7:3 (140px * 60px), the bigger it looks.
In other words, the only simple adjustment here would be using the square Deutsche Bank logo, or something else closer to the mentioned aspect ratio, that would make it appear larger, similar to the Deutsche Bahn that's next to it...

If you wish to replace the logo, the bot allows updating them, so you can simply create new issue with the preferred logo using the same company name and URL.

We do not really archive originals of the already resized logos, so gathering and resizing all of the logos might be a time consuming task. But if you prefer a different layout of the carousel and the participant listing, please specify that design update in a separate issue in details.

Thanks.
