### ISSUE TITLE
Copy for Red Hat OpenShift on IBM Cloud SIG Page

### ISSUE THREAD

**Issue by starbolin** [openshift-cs/commons.openshift.org#1709]
Hello, here is my suggested copy for the SIG page: https://commons.openshift.org/sig/OpenShiftOnIBMCloud.html

The principal purpose of the Red Hat OpenShift on IBM Cloud Special Interest Group is to collaborate and share tips & tricks for Day 1 Build/Day 2 Operations with OpenShift environments on IBM Cloud.
 
Topics Covered
-  OpenShift tools and APIs for a single, consistent experience across hybrid environments or different cloud providers.
-  Protect cluster infrastructure, isolate compute resources, encrypt data, and ensure security compliance.
-  Quickly set up a CI/CD with Jenkins or deploy a variety of apps in a guided experience that's fully integrated into your OpenShift cluster.
- Deploy and scale workloads with a managed master that is automatically spread across zones within a region for high availability.
- Use built-in services for monitoring, logging, load-balancing, storage, and security.
-  Integrate AI with a range of Watson APIs to extend the power of your apps.

 
About [Red Hat OpenShift on IBM Cloud](https://www.ibm.com/cloud/openshift)
AIOps is as much about operations as it is about development. This Special Interest Group is a way for like-minded engineers to discuss and share information applying AI to aid in deploying and maintaining OpenShift at scale.

**Comment by starbolin** [comment]
https://commons.openshift.org/sig/OpenShiftOnIBMCloud.html

That's the link for the SIG page...not the gibberish up top.

**Comment by jiri-fiala** [comment]
For the attention of @dmueller2001

**Comment by dmueller2001** [comment]
live now

**Comment by starbolin** [comment]
Sweet. Thanks.
