### ISSUE TITLE
knewcomerRH & botchagalupe

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1819]
grant edit privs to https://github.com/knewcomerRH and https://github.com/botchagalupe to commons.openshift.org so they can update/merge/upload content for the devsecops SIG landing page

**Comment by wgordon17** [comment]
`Write` access granted to https://github.com/knewcomerRH and https://github.com/johnmwillis-rht. They should each have an invitation email to accept
