### ISSUE TITLE
add Fermilab to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1850]
Company: Fermilab
URL: https://fnal.gov/
Logo: 
![image](https://user-images.githubusercontent.com/14938461/82303368-282a0d00-99bb-11ea-9915-c9edf9e4cc74.png)

**Comment by jiri-fiala** [comment]
The white logo on a transparent background was replaced with a screenshot of the same logo found at final.gov.
