### ISSUE TITLE
add Proxy  to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#1932]
Company: Proxy
URL: https://www.proxy.nl/
logo: https://www.proxy.nl/wp-content/uploads/2019/12/Logo-340x156-300x138.png

**Comment by jiri-fiala** [comment]
@dmueller2001, the logo processing bot does not support WebP; please link only PNG or JPEG images (the originally provided logo path was `https://www.proxy.nl/wp-content/uploads/2019/12/Logo-340x156-300x138.png.webp`)
