### ISSUE TITLE
Update all forms on commons.openshift.org site

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#312]
1/  Feed into Eloqua so we can maintain/update privacy compliance
2/  All forms are SPAM compliant in that they 
    a)  Have a CAPTCHA or
    b)  Have a tick box that allows to customer to say they are real an not a robot
3/  Ensure all contacts captured through any means are managed the the welcome pack process to ensure double-opt-in

**Comment by developercorey** [comment]
Do you have the needed information to post the form data into Eloqua?

Can you elaborate on #3?  It seems like that would be handled through the Eloqua system?

**Comment by dmueller2001** [comment]
This is part of the new corporate mandate from Martin Klaus & the Corporate Marketing team. You'll need to coordinate with him to get access to the welcome pack process.

**Comment by jiri-fiala** [comment]
The Machine Learning SIG form is excluded from this request (it is not going to be processed in Eloqua, unless requested in a separate Issue).
