### ISSUE TITLE
Feature the upcoming events more prominently on the home page of commons.openshift.org 

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#485]
add a new section called "UpComing Events" above the "Find Your Commonality" section to the home page with the agenda style calendar 

below is the widget to embed:

<script class="ai1ec-widget-placeholder" data-widget="ai1ec_superwidget" data-action="agenda">
  (function(){var d=document,s=d.createElement('script'),
  i='ai1ec-script';if(d.getElementById(i))return;s.async=1;
  s.id=i;s.src='//live-timely-objzoywz.time.ly/?ai1ec_js_widget';
  d.getElementsByTagName('head')[0].appendChild(s);})();
</script>

**Comment by jiri-fiala** [comment]
@dmueller2001, [here's](http://comm-jfiala.rhcloud.com/) an example how it could look like. There are some things that are questionable:
- There is an apparent page reflow now, as the calendar is loaded from external source. This could be less apparent if the calendar is placed further down the page.
- The section has no direct link in the top menu as there are already "upcoming events" in the "Briefings" menu.
- The calendar does not look good when placed on a gray background, so I used two white sections next to each other.
- The gap between the first and second section is due to the dynamic dropdown in the eloqua form with hardcoded iframe height. That can't be avoided with the iframe.

Please let us know what you think.

**Comment by dmueller2001** [comment]
@jiri-fiala the agenda content should be trimmed down to only show the 3-4 items..

try this widget 

<script class="ai1ec-widget-placeholder" data-widget="ai1ec_agenda_widget" data-events_seek_type="events" data-events_per_page="4" data-days_per_page="100">
  (function(){var d=document,s=d.createElement('script'),
  i='ai1ec-script';if(d.getElementById(i))return;s.async=1;
  s.id=i;s.src='//live-timely-objzoywz.time.ly/?ai1ec_js_widget';
  d.getElementsByTagName('head')[0].appendChild(s);})();
</script>

**Comment by dmueller2001** [comment]
can we make the eloqua form smaller? using smaller fonts in the descriptive text and tightening up the spacing in/around the form itself?

**Comment by jiri-fiala** [comment]
@dmueller2001, I have reduced the bottom padding of the form section,  but the Eloqua form is served in an iframe, and is out of our control.
- It seems to me that we can simply remove the "Join Now" header on the form and make the "Submit" button caption to be "Join Now" instead to save some vertical space.
- The height of the iframe is set to acomodate the *Company* dynamic drop down. If the company name would not feature the drop down, or be shorter, we can reduce the total height of the iframe.

Eloqua form adjustments ^ are out of our control, please ask Greg to modify the form, if those suggestions seem reasonable to you.

The calendar widget has been updated as requested, displaying 4 items only now. If you can, I would recommend to modify it as follows:
- adjust the colors of the calendar widget with those 4 items so it possibly fits better into the page style
- modify the "Add" dropdown menu position to be rendered above the button (currently it renders only three first menu items in the section).

A preview is available [**here**](http://comm-jfiala.rhcloud.com/).

**Comment by dmueller2001** [comment]
two things:
let's try the wider version of the calendar so there is NOT as much white space in that section:

<script class="ai1ec-widget-placeholder" data-widget="ai1ec_superwidget" data-action="agenda" data-events_limit="5">
  (function(){var d=document,s=d.createElement('script'),
  i='ai1ec-script';if(d.getElementById(i))return;s.async=1;
  s.id=i;s.src='//live-timely-objzoywz.time.ly/?ai1ec_js_widget';
  d.getElementsByTagName('head')[0].appendChild(s);})();
</script>

AND

under the calendar widget add a link to 'For More Events >' and link it to http://commons.openshift.org/events.html

**Comment by jiri-fiala** [comment]
@dmueller2001, the [preview](http://comm-jfiala.rhcloud.com/) has been updated with the change.
(The time.ly widget does not work properly when served over https again though)

**Comment by dmueller2001** [comment]
can you also add in section #events so that https://commons.openshift.org#events jumps to that section 

it looks good other than that missing #

**Comment by jiri-fiala** [comment]
@dmueller2001, the section uses the `#upcoming` id already, do you want to change it to `#events` indeed? (using `commons.openshift.org/events.html` vs `commons.openshift.org/#events` could be confusing, as they lead to slightly different calendar views)

**Comment by dmueller2001** [comment]
agreed, #upcoming works fine and avoids the confusion..

**Comment by jiri-fiala** [comment]
This is going to be released together with #484, once ready.
