### ISSUE TITLE
Change the title above the briefings calendar on the home page

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#496]
![titlechangefromevents2briefings](https://user-images.githubusercontent.com/4029488/30071389-5d7b22f0-921b-11e7-8779-a76aff121feb.png)

Change the title from "UpComing Events" to "Upcoming Briefings" 
Change the "More Events ->" button to "More Briefings ->"

(first stage of changes to the events section which can be done in this iteration)

**Comment by jiri-fiala** [comment]
This is prepared to be released together with #484.
