### ISSUE TITLE
Add a new SIG for "Machine Learning on OpenShift"

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#508]
create landing page with a sign-up form and add it to the #interest section on home page

add a link on http://commons.openshift.org/index.html#interests

using:
Title: Machine Learning on OpenShift
Desc: Discuss, develop and disseminate best practices for deploying and Machine Learning  applications and workloads on OpenShift.

add new landing page for Machine Learning on OpenShift and form to collect interested participants.

using

Title: Machine Learning on OpenShift

Description:

The principal purpose of the Machine Learning on OpenShift Special Interest Group is to discuss, develop and disseminate best practices for deploying and managing Machine Learning workloads and applications on OpenShift built using (but not limited to) TensorFlow, Apache Spark and other Open Source ML/AI frameworks.

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
This is prepared for previewing and to be released together with #484, #485, #496 and the rest of the new SIG forms, once tested and approved.

**Comment by dmueller2001** [comment]
@jiri-fiala @wgordon17 as a back-up in case the Eloqua forms are not ready for the Dec 4th launch of the ML SIG, could you replace the V3 SIG and it's google form with one for ML and create the landing page? I'd like to flag a few specific blog posts for the landing page and make sure the content looks decent for launch.

**Comment by jiri-fiala** [comment]
@dmueller2001, the requested back-up using the old form style is prepared in pull request #535, in case it needs to be deployed quickly.
[Blog posts tagged `machine-learning`](https://blog.openshift.com/tag/machine-learning/) are fetched.

**Comment by dmueller2001** [comment]
@jiri-fiala let's push the old-style form live for machine learning - no word from the Eloqua team and i need it live and tested this week for a blog on friday..

**Comment by jiri-fiala** [comment]
@dmueller2001, I'm closing this one, according to the email discussion, this form should not be migrated to Eloqa for the time being. If that would be required in future, please open a new Issue. Thanks.
