### ISSUE TITLE
add DMD Consulting to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#560]
url: http://dmdnetworks.com/
logo: tbd
![screen shot 2018-05-04 at 3 48 46 am](https://user-images.githubusercontent.com/4029488/39624435-1fdc5432-4f4e-11e8-8fc8-5fb5db77dcec.png)
@jiri-fiala @wgordon17  added a screenshot of their text logo from site - please add to the site list as is for now..

**Comment by wgordon17** [comment]
@dmueller2001 Any closer to having a valid logo?
