### ISSUE TITLE
add apis-it.hr to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#599]
url: https://www.apis-it.hr/apisit/index.html
logo: https://www.apis-it.hr/apisit/images/logo.png (needs a black background)

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
It looks like APIS IT [provides](https://www.apis-it.hr/apisit/apis.nsf/53CA202727279A1BC1257FF00029001E/$FILE/APIS_IT_logo_20141211.pdf) alternate logos too, I'm going to use one with white background (without the text that would be to small for this page):

![apisit](https://user-images.githubusercontent.com/14938461/36423789-7aed70ae-1641-11e8-81a9-6cacf70ed422.png)
