### ISSUE TITLE
add london gathering videos to commons site

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#607]
link to playlist: https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqfhzC5ds3sMju7KKNzdd0xy

link to the agenda (so you have a few words of description/titles) http://london.openshiftgathering.com/

the 3:15 p.m. Panel: OpenShift in Financial Services - moderated by Chris Milstead (RedHat) was NOT recorded and as there were legal/privacy issues that we needed to respect at the event.

@jiri-fiala @wgordon17

**Comment by jiri-fiala** [comment]
@dmueller2001, could you please add all panelists' names to [this video](https://youtu.be/Dah1BEYW190?t=1m47s); I would hate to cripple anyone's name.
Thank you.

**Comment by dmueller2001** [comment]
@jiri-fiala here's the logo 
![astellent logo](https://user-images.githubusercontent.com/4029488/36609060-8c5d84f0-1880-11e8-982a-78562ef9dacb.jpg)

**Comment by dmueller2001** [comment]
Kalbir Sohi - Drie

Justin Cook - Secnix

James Curran - Deloitte Digital

Bill Mew - UKCloud
