### ISSUE TITLE
add runways.co to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#616]
url: https://www.runways.co/
logo: https://www.runways.co/assets/images/runways-airport-signage@100%25.jpg

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
@dmueller2001, the logo link returns 404; is it ok to use the [logo from homepage](https://www.runways.co/assets/images/RWY-Homepage.png)?

**Comment by wgordon17** [comment]
@jiri-fiala From @dmueller2001...ok to use homepage logo

**Comment by dmueller2001** [comment]
yes, use the logo from their homepage

**Comment by dmueller2001** [comment]
![rwy-logo 2x](https://user-images.githubusercontent.com/4029488/37495314-e2260738-2869-11e8-9fb2-ac4326833ce8.png)
![rwy-logo 1000x500](https://user-images.githubusercontent.com/4029488/37495315-e23eb404-2869-11e8-9c9c-719cc92e42fb.png)

@jiri-fiala the marketing folks from runway asked us to use one of the two above images rather than the one from their website
