### ISSUE TITLE
add intesa san paolo to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#648]
url: https://www.intesasanpaolo.com/it/persone-e-famiglie.html
logo: 
![intesasanpaolo](https://user-images.githubusercontent.com/4029488/40012690-4562615a-5760-11e8-833c-8b5ea3ac86a0.jpg)

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
The following logo with transparent background will be used (it's of better quality when resized):
![image](https://user-images.githubusercontent.com/14938461/40046643-bc94a3b4-582d-11e8-9e72-2af821b4da8a.png)
@dmueller2001, if the "group services" logo is required, please let me know.

**Comment by dmueller2001** [comment]
that logo works better and is good to use..
