### ISSUE TITLE
add anz to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#657]
url: https://www.anz.com.au/personal/
logo: https://www.anz.com.au/content/dam/anzconz/images/common/promopages/logo-promo-anz-small.png

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
The white logo with transparent background is not suitable for our page, I'm going to use this one instead:
![image](https://user-images.githubusercontent.com/14938461/40163752-f0a845ee-59b7-11e8-8fa1-50458e0b22b2.png)
