### ISSUE TITLE
create landing page for Seattle, Washington Gathering 

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#680]
Language: English
Date: December 10, 2018
Location: Seattle, Washington
Registration: via CNCF.io 
https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2018/attend/register/
Venue: Washington Convention Center Seattle Washington USA

Do not link to navigation yet

**Comment by wgordon17** [comment]
Resolved by #689
