### ISSUE TITLE
add Arista to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#684]
url: https://www.arista.com/en/

logo: https://www.arista.com/templates/arista_v2/img/logo_arista.png

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
The white logo on transparent background is not suitable for us, the following logo from [Arista blog](https://blogs.arista.com/blog) is going to be used instead:

![image](https://user-images.githubusercontent.com/14938461/41542326-f844178a-7314-11e8-8394-37061da331af.png)
