### ISSUE TITLE
add another section for content in the gathering.yaml file

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#697]
under the event overview section there is a paragraph of content that is still hardcoded into the template

"By being co-located in Austin with KubeCon at the Hilton Austin, the OpenShift Commons Gathering will provide a platform for showcasing a full range of technologies that support the OpenShift ecosystem and help bring cloud native project communities together. We strongly encourage you to partake in the full week of events. '

Please call this metadata tag something similar to "EventOverviewFooterText"

![screen shot 2018-06-20 at 9 45 31 am](https://user-images.githubusercontent.com/4029488/41672509-f2694e10-746e-11e8-9f67-ba01e3faf596.png)

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
@dmueller2001, a fix is prepared in #698 . The original `additional_info` is now renamed to `event_footer_text` and properly used.

The remaining longer hardcoded text paragraphs are above the registration buttons:

> Where users, partners, customers, contributors and upstream project leads come together to collaborate and work together on OpenShift.

...and as lead text for the schedule:

> The day will have a mix of keynotes, panels, ted-style talks, SIG break-out sessions, plenty of time to network over local craft beers and be continuously fuelled by local baristas.

These seemed quite universal for me, but the yml can support changing them too, if you wish.
