### ISSUE TITLE
Add a new SIG for "Operator Framework" 

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#709]
create landing page with a sign-up form and add it to the #interest section on home page

add a link on http://commons.openshift.org/index.html#interests

using:
Title: Operator Framework
Desc: The Operator Framework is an open source toolkit to manage Kubernetes native applications, called Operators, in an effective, automated, and scalable way. This SIG will 
discuss, develop and disseminate best practices for building and managing Operators.

add new landing page for the Operator Framework SIG and form to collect interested participants.

using

Title: Operator Framework

Description:

The principal purpose of the Operator Framework SIG is to discuss, develop and disseminate best practices for building  Operators, using Operators and help grow the Operator ecosystem by engaging and learning from Operator authors, users and contributors to the Operator Framework itself.

Pull any blogs with the tag "Operators" for use in the blog section of the landing page for the Operator Framework SIG

@wgordon17 @jiri-fiala @robszumski @spahl

**Comment by robszumski** [comment]
sounds good to me
