### ISSUE TITLE
add Aman to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#720]
url: https://www.aman.de/
logo: tbd

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
Aman has already been added in #592, I'm going to update the logo we currently have:

![image](https://user-images.githubusercontent.com/14938461/42626295-380378b2-85ca-11e8-9a8c-66b9839ba757.png)

...with the new one:

![image](https://user-images.githubusercontent.com/14938461/42626285-3062871a-85ca-11e8-8370-07df997c06df.png)
