### ISSUE TITLE
translate Buenos Aires Content from English to Spanish

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#724]
@mbetanco will translate in comment 

pricing:
      - label: "RSVP Required"
        price: "Free"
    lead_text: >-
      This OpenShift Commons Gathering will be held in Buenos Aires at the <a href="https://www.wscc.com/" target="_blank">Washington State Convention Center</a>!
    info_text: >-
      The OpenShift Commons Gathering brings together experts from all over the world to discuss container technologies, best practices for cloud native application developers and
      the open source software projects that underpin the OpenShift ecosystem. The Buenos Aires event will gather developers, devops professionals and sysadmins together to explore
      the next steps in making container technologies successful and secure.
    event_footer_text: >-
      By held in Bueons Aires , the OpenShift Commons Gathering will provide a platform for showcasing a full range of technologies that
      support the OpenShift ecosystem and help bring LATAM cloud native project communities together. We strongly encourage you to partake in the full week of events.

**Comment by dmueller2001** [comment]
info_text should read:

"El OpenShift Commons Gathering tendrá como eje las charlas a cargo de usuarios finales sobre implementaciones de OpenShift en modo de producción, en las que compartirán sus casos de uso, aprendizajes y buenas prácticas con expertos de todas partes del mundo. También analizará las tecnologías de contenedores, las buenas prácticas del desarrollo de aplicaciones nativas de la nube y los proyectos de software open source que apuntalan al ecosistema OpenShift para llevar a OpenShift al siguiente nivel del cloud computing nativo. El evento reunirá a desarrolladores, profesionales de DevOps y administradores de sistemas que explorarán y colaborarán para lograr que OpenShift y las tecnologías de contenedores sean exitosas y seguras a gran escala."

**Comment by jiri-fiala** [comment]
closed by #728
