### ISSUE TITLE
add prophetstor to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#730]
url: http://www.prophetstor.com/
logo: https://i1.wp.com/www.prophetstor.com/wp-content/uploads/2017/05/prophetstor_white_logo.png?fit=143%2C62

@wgordon17 @jiri-fiala 

metatag: Machine Learning < just a note for diane

**Comment by jiri-fiala** [comment]
The white font logo is not suitable, I'm going to use [their Twitter account](https://twitter.com/prophetstor) logo:
![image](https://user-images.githubusercontent.com/14938461/42624862-b32679d0-85c6-11e8-8e7e-8fce425f79b0.png)
