### ISSUE TITLE
Openshift Commons Gathering Buenos Aires | Agenda

### ISSUE THREAD

**Issue by CamiP2018** [openshift-cs/commons.openshift.org#743]
Hi,
I need to make the following changes in the agenda to put it all in Spanish. Let's use the time as our main guide to talk about each presentation, as the language can be sometimes confusing:

I'll separate the information always following this order, so you can know what I'm possibly saying even though it's in Spanish:
- in the first line always: the time and the title
- in the second line of the same talk: the name of the speaker, job role, company (an if it is a customer the country). Whenever I put a new time slot, it means I change to the following talk of the Commons. If in doubt do not hesitate in contacting me:

9:00 am | Acreditación

9:30 am | Bienvenidos al Commons: Fomentar una colaboración que funcione. 
Santiago Sinelnicof, Senior Solution Architect | Red Hat

9:40 am | State of the Union: Red Hat OpenShift
Reza Shafii, OpenShift BU Vice President | Red Hat

10:30 am | Estudio de caso: El Banco Online
Cristian Roldán, Paas Manager | Produban | España

11:30 am | Coffee Break

11:45 am | Programa de Adopción de Contenedores 
Trevor Quinn, Container and Paas Senior Manager | Red Hat

12:30 pm | Estudio de Caso: OpenShift en el Ministerio de Modernización

13:00 pm | Lunch

14:00 pm | Presentación Intel

14:15 pm | Estudio de Caso: OpenShift en GetUp Cloud
Mateus Caruccio | GetUp Cloud | Brazil

14:45 pm | Panel de Servicios Financieros
Banco Hipotecario, Banco Galicia, Banco Supervielle, Gire, Gestión Compartida | Argentina

15:30 pm | Estudio de caso: OpenShift en AGESIC 
Javier Barreiro, Technology Director | AGESIC | Uruguay

16:00 pm | Estudio de caso: OpenShift en Banco Itaú 
Martín D'Elía, CIO | Banco Itaú | Argentina

16:15 pm | Estudio de caso: OpenShift en Previred 
Miguel Cáceres | Previred | Chile

16:45 pm | Estudio de caso: OpenShift en Conservador de Bienes Raíces de Santiago 
Miguel Cáceres | Previred | Chile

17:15 pm | El futuro de OpenShift
Santiago Sinelnicof, Senior Solution Architect | Red Hat

17:30 pm | Happy Hour! Pizzas y Cervezas

Thanks so much for your help! 

@dmueller2001

**Comment by jiri-fiala** [comment]
closed by several commits updating the agenda
