### ISSUE TITLE
add Royal Mail to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#744]
url: https://www.royalmail.com/
logo: https://www.royalmail.com/sites/all/themes/royalmail2017/img/royalmail-logo.png

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
A slightly larger logo will be used (instead of the linked one that is 100px wide):
![image](https://user-images.githubusercontent.com/14938461/43199461-5261aa92-9012-11e8-86d5-3f981c4662ce.png)
