### ISSUE TITLE
OpenShift Commons Gathering Buenos Aires | General Changes

### ISSUE THREAD

**Issue by CamiP2018** [openshift-cs/commons.openshift.org#745]
Hi,

I need to make other changes in the landing page of the Buenos Aires's Commons. I'll list them so I can concentrate the changes in one issue. I wrote some notes in brackets to clarify some information:

1) Change this block of text placed below the 'Event Overview' (please translate this heading to the Spanish 'Descripción del Evento'): 

Where users, partners, customers, contributors and upstream project leads come together to collaborate and work together on OpenShift.

To the following one: 
Donde se congregan usuarios, socios, clientes, colaboradores y líderes de proyectos de desarrollo para colaborar y trabajar codo a codo con OpenShift.

Delete the button 'Purchase tickets now' as it is a free event.

2) I need to replace the information that is placed in the right place of the Event Overview white box:
a) 'Where: Buenos Aires Argentina, Red Hat offices' for this Spanish text: DÓNDE (means 'where' in Spanish) | Espacio Darwin. Av. Cnel. Niceto Vega 5350, C.A.B.A. (this is the adress of the place).
b) 'When': CUÁNDO (means 'when' in spanish) | 2 de agosto de 2018 (this is the date)
c) 'Price': COSTO (means 'price' in spanish) | RSVP requerido: Sin costo (this is the translation for the English: price | RSVP required: free)
d) Button 'purchase tickets now': 'Confirme su asistencia' (this is the Spanish for 'register'). Button should go to the Event Brite link of the event: https://www.eventbrite.com/myevent?eid=47432137801

3) I need to replace the information in the text block 'Venue' that is in the bottom of the landing page (please translate the heading Venue to the Spanish 'Sede del Evento':
a) 2 de agosto de 2018 (this is the date) | 9:00 a 19:00 horas (this is the time)
Espacio Darwin (this is the name of the place)
Av. Cnel. Niceto Vega 5350 (this is the adress of the place and the map should be placed in this adress).

3) Please replace the heading Shedule for the Spanish 'Agenda'. I also need help to replace this text that's placed below:

The day will have a mix of keynotes, panels, ted-style talks, SIG break-out sessions, plenty of time to network over local craft beers and be continuously fuelled by local baristas.
See session video recordings from previous gatherings » 

For the Spanish version: 

La jornada ofrecerá una serie de disertaciones, paneles y charlas al estilo TED así como también espacios de networking.
Vea las ediciones anteriores de otros OpenShift Commons »  

4) The buttons: 'overview', 'schedule', 'speakers' and 'venue' of the main search menue of the landing page should say:
'Descripción del Evento' (means 'overview').
'Agenda' (means 'schedule')
'Disertantes' (means 'speakers')
'Sede del Evento' (means 'venue')

Should you have any doubts, do not hesitate in contacting me.

Regards and thanks for your help in advance.

@dmueller2001

**Comment by dmueller2001** [comment]
I will change "Purchase Tickets" to "RSVP" as well

**Comment by dmueller2001** [comment]
@wgordon17 

in which file do i change:

'Descripción del Evento' (means 'overview').
'Agenda' (means 'schedule')
'Disertantes' (means 'speakers')
'Sede del Evento' (means 'venue')

and if i do is it a global change thus showing up on even the english pages?
