### ISSUE TITLE
add  deutschebahn to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#753]
url: https://www.deutschebahn.com/de
logo: https://www.deutschebahn.com/resource/crblob/1174354/be43f4a811d7d1ecbc4baa0a2c7695e5/betreiberlogo_startseite_de-data.png

@wgordon17

**Comment by jiri-fiala** [comment]
A slightly larger logo will be used:
![image](https://user-images.githubusercontent.com/14938461/43201220-21509a66-9018-11e8-874e-7bd5ea04d891.png)
