### ISSUE TITLE
OpenShift Commons Buenos Aires | Map of the Venue (wrong adress)

### ISSUE THREAD

**Issue by CamiP2018** [openshift-cs/commons.openshift.org#758]
Hi,

I need to revise the map from the Venue section of the landing page. It doesn't match the correct adress which is: Av. Cnel. Niceto Vega 5350, Buenos Aires (Google Maps link: https://goo.gl/maps/aKdEuUM8Mbt). Could you please help me?

Thanks

@dmueller2001

**Comment by jiri-fiala** [comment]
fixed by #763
