### ISSUE TITLE
update the Diamanti logo on OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#822]
company: Diamanti
url: https://diamanti.com/
logo: 
![diamanti logo](https://user-images.githubusercontent.com/4029488/46043966-506e4500-c0ce-11e8-9058-7f4730612d95.jpg)

@wgordon17 @jiri-fiala

**Comment by wgordon17** [comment]
@jiri-fiala Next week, I'd like to look into letting the bot be able to *replace* logos ;)
