### ISSUE TITLE
cross link RHT Connect EAP operator pages to commons pages

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#884]
https://connect.redhat.com/operators-eap add a call-out and link to the EAP program to both the operators.html page and the OpenShiftOperators.html page

@alexmarple
@dmueller2001

**Comment by jiri-fiala** [comment]
@dmueller2001, this got buried a bit. One of the options on how to link the Early Access Program (if it is still relevant) is to put something like this on bottom of both pages:
![image](https://user-images.githubusercontent.com/14938461/56903429-904e3e00-6a9c-11e9-86ae-e65eed2bd9b3.png)

If you'd like a specific text copy, position, style or anything else, please provide more details.

**Comment by dmueller2001** [comment]
operatorhub.io
