### ISSUE TITLE
add s-und-n.de to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#890]
Company: S & N 
Url: https://www.s-und-n.de
logo: 
![sn-logo](https://user-images.githubusercontent.com/22222756/48563047-78557a00-e8c1-11e8-88af-3439139853ee.png)

**Comment by jiri-fiala** [comment]
The www.s-und-n.de is [serving incomplete certificate chain](https://www.ssllabs.com/ssltest/analyze.html?d=www.s-und-n.de) and the logo bot is failing on `javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` when attempting to retrieve [the logo](https://www.s-und-n.de//assets/tpl/img/sn-logo.png) (tested locally with openjdk 1.8.0_181).

The image resizer logging would use some improvement to indicate the exact exception.

**Comment by jiri-fiala** [comment]
The original link to the logo (`https://www.s-und-n.de//assets/tpl/img/sn-logo.png`) was replaced with the logo uploaded to GitHub, which avoids the certificate error on S&N's website. This will be processed with the next run of the Jenkins job.
