### ISSUE TITLE
add paychex to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#965]
company: PayChex
url: https://www.paychex.com/
logo: ![pay_blue 1](https://user-images.githubusercontent.com/22222756/51336948-de8e8280-1a53-11e9-92df-6abcff844a0e.jpg)

**Comment by dmueller2001** [comment]
@wgordon17 any reason this didn't get automatically added to the Commons?

**Comment by wgordon17** [comment]
@dmueller2001 It's an SSL error with the original URL. Downloading the image and adding it manually above should fix this 👍
